### ISSUE TITLE
Create MCQA for Date methods

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/who-wants-to-be-a-javascriptaire#18]
Please create an MCQA to be added as question number 32.

The multiple choice question should be on the topic "Date" methods. The difficulty level should be "Medium/Hard"

**Tasks**: 
- [x] add your code to 032 folder under code
- [x] add your question to 32 in README.md file
- [ ] create a video explanation and upload on YouTube (optional)

**Explanation:**
- getFullYear(): returns YYYY
- getMonth(): returns month idx
- getDate()
- getDay()
- UTC Methods: getUTCYear(), getUTCMonth() etc
- setFullYear(YYYY)
- setMonth(M), setDate(D), setDay(D)
- Date.parse(dateString) returns milliseconds or new Date(dateString)

**Sample interview question for inspiration**
- Get current month ?
- Find the date before 50 days of a given date.
- What will be the output of `new Date(35)`

**Comment by murat114** [comment]
Hello,
I would like to take on the task.

**Comment by kirandash** [comment]
Thanks @murat114  🙏 for showing your interest! I have now assigned the task to you.

If you need any help, you can comment here or reach me on discord at:

https://discord.gg/62VR3MMCVm

And if you like this project, please do show your support by leaving a star ⭐️ for more visibility

**Comment by kirandash** [comment]
Thanks @murat114 for your contribution.
