### ISSUE TITLE
Create MCQA for Object literal

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/who-wants-to-be-a-javascriptaire#24]
Please create an MCQA to be added as question number 34.

The multiple choice question should be on the topic "Object literal". The difficulty level should be "Medium/Hard"

**Tasks**: 
- [x] add your code to 034 folder under code
- [x] add your question to 34 in README.md file
- [ ] create a video explanation and upload on YouTube (optional)

**Explanation:**
- There are many ways to create an object
   - class `Object` is one way
- Object allows us to create a container to put multiple data type. It's a key value data structure
- Object has properties and methods

**Sample interview question for inspiration**
- Can you have dynamic keys with object literal?
   - yes, `const tv = "pCode"; let obj3 = { [tv]: 1001 }`
- How can you add read-only properties to an object? (Level: Hard, since most devs can't answer this)
   - `Object.defineProperty()` and `Object.create()`
- What is property value short hand with object literal?
   `let obj = { pCode, pName }` : ES6
- What will be the output of this code? Explain the reason why?
   ```
    let obj={a:'First'};
    let obj1 = obj;
    obj1.a="Second";
    console.log(obj.a);
    ```
    - ans: "Second", since Object assigned with = have same reference
- How can we create a clone or separate copy of an object literal?
   -  `let obj1 = Object.assign({}, obj2) or let obj1 = {...obj2}`

**Comment by RahulRana701** [comment]
hi @kirandash I would like to work on that , can you assign it to me..

**Comment by kirandash** [comment]
Thanks for your contribution @RahulRana701 🙏
