### ISSUE TITLE
Create MCQA for class, class expression and static members

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/who-wants-to-be-a-javascriptaire#27]
Please create an MCQA to be added as question number 37.

The multiple choice question should be on the topic "class, class expression and static members". The difficulty level should be "Medium/Hard"

**Tasks**: 
- [x] add your code to 037 folder under code
- [x] add your question to 37 in README.md file
- [ ] create a video explanation and upload on YouTube (optional)

**Explanation:**
- class is to create a blueprint or design or prototype
- To create class:
   - in ES6 we have `class` keyword
   - in ES5 we had constructor fn

**Sample interview question for inspiration**
- How can you create a class?
- When does constructor() called?
- Can we have dynamic property or method names in a class?
   - Yes, Ex: `[getName]`
- What is a class expression?
   - `const House = class{}`
- What are static members in a class? What is the purpose of defining them as static?
   - static members can be created using static keyword before property or method
   - Application: for creating a module which has services where we do not need to instantiate a class, in those case we create those members as static props / methods.
- How can you call another static method from a class?

**Comment by kr-abhi55** [comment]
i'm interested

**Comment by kr-abhi55** [comment]
i'm interested

**Comment by kr-abhi55** [comment]
but i can't able to make video

**Comment by kirandash** [comment]
> i'm interested

Thanks @kr-abhi55 🙏 for showing your interest! I have now assigned the task to you.

If you need any help, you can comment here or reach me on discord at:

https://discord.gg/62VR3MMCVm

And if you like this project, please do show your support by leaving a star ⭐️ for more visibility

**Comment by kirandash** [comment]
> but i can't able to make video

that's totally optional. no worries. I can create video later in a separate task

**Comment by kr-abhi55** [comment]
do i have to create only one problem which is mix of class ,class expression and staic members

**Comment by kirandash** [comment]
> do i have to create only one problem which is mix of class ,class expression and staic members ?

not necessarily. But I thought it would be nice if we can cover all three topics in a single question. If you feel like creating three different questions then let me know and I can create two more issues for Question 38 and 39. And we can cover the topics in different MCQs.

**Comment by kr-abhi55** [comment]
ok, i will make a problem which is mix of all

**Comment by kirandash** [comment]
@kr-abhi55 Thanks a lot for your contribution. Your PR was really good. It was nice to see how you added all three topics in one question and also the explanation was to the point.
